### ISSUE TITLE
EOFError and ConnectionResetError in the multiprocessing connection.py

### ISSUE THREAD

**Issue by foreversadan** [jacobkrantz/VLN-CE#14]
![image](https://user-images.githubusercontent.com/3351143/112843867-9a46a480-90ea-11eb-9202-53d64765fe04.png)
After I installed habitat-sim, habitat-lab and VLN-CE in the README.md successfully, and run the command "python run.py --exp-config vlnce_baselines/config/rxr_configs/rxr_cma_en.yaml --run-type train", I got this error.

Did I do something wrong?

**Comment by jacobkrantz** [comment]
This could be for many different reasons. Have you been able to successfully run the Habitat-Lab [example script](https://github.com/facebookresearch/habitat-lab/blob/master/examples/example.py)? The multiprocessing error could be hiding the real issue. Switching from `habitat.VectorEnv` to `habitat.ThreadedVectorEnv` in the `construct_envs` function should provide a more useful message. One reason I've seen this error is from having wrong file paths in the config.

**Comment by MyShepherd666hzb** [comment]
![Uploading b2658823aa0b827abfce974dc3b300f.jpg…]()
I also got the same error. I looked at the previous related content and thought there might be a problem with the dataset. Could you please give me a solution?

**Comment by missTL** [comment]
Have you solved this problem?


Traceback (most recent call last):
  File "run.py", line 92, in <module>
    main()
  File "run.py", line 43, in main
    run_exp(**vars(args))
  File "run.py", line 84, in run_exp
    trainer.train()
  File "/home/zengshuang.zs/new/VLN-CE/vlnce_baselines/recollect_trainer.py", line 77, in train
    dataset = TeacherRecollectionDataset(self.config)
  File "/home/zengshuang.zs/new/VLN-CE/vlnce_baselines/common/recollection_dataset.py", line 49, in __init__
    self.initialize_sims()
  File "/home/zengshuang.zs/new/VLN-CE/vlnce_baselines/common/recollection_dataset.py", line 71, in initialize_sims
    observations = self.envs.reset()
  File "/home/zengshuang.zs/g3D-LF/habitat-lab/habitat/core/vector_env.py", line 384, in reset
    results.append(read_fn())
  File "/home/zengshuang.zs/g3D-LF/habitat-lab/habitat/core/vector_env.py", line 97, in __call__
    res = self.read_fn()
  File "/home/zengshuang.zs/g3D-LF/habitat-lab/habitat/utils/pickle5_multiprocessing.py", line 68, in recv
    buf = self.recv_bytes()
  File "/home/zengshuang.zs/anaconda3/envs/vlnce/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/zengshuang.zs/anaconda3/envs/vlnce/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/zengshuang.zs/anaconda3/envs/vlnce/lib/python3.6/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Exception ignored in: <bound method VectorEnv.__del__ of <habitat.core.vector_env.VectorEnv object at 0x7f62aae70518>>
Traceback (most recent call last):
  File "/home/zengshuang.zs/g3D-LF/habitat-lab/habitat/core/vector_env.py", line 588, in __del__
    self.close()
  File "/home/zengshuang.zs/g3D-LF/habitat-lab/habitat/core/vector_env.py", line 456, in close
    read_fn()
  File "/home/zengshuang.zs/g3D-LF/habitat-lab/habitat/core/vector_env.py", line 97, in __call__
    res = self.read_fn()
  File "/home/zengshuang.zs/g3D-LF/habitat-lab/habitat/utils/pickle5_multiprocessing.py", line 68, in recv
    buf = self.recv_bytes()
  File "/home/zengshuang.zs/anaconda3/envs/vlnce/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/zengshuang.zs/anaconda3/envs/vlnce/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/zengshuang.zs/anaconda3/envs/vlnce/lib/python3.6/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError:

**Comment by Hyzz2214** [comment]
I meet the same problem ,have you solved it? #

> Have you solved this problem?
> 
> Traceback (most recent call last): File "run.py", line 92, in main() File "run.py", line 43, in main run_exp(**vars(args)) File "run.py", line 84, in run_exp trainer.train() File "/home/zengshuang.zs/new/VLN-CE/vlnce_baselines/recollect_trainer.py", line 77, in train dataset = TeacherRecollectionDataset(self.config) File "/home/zengshuang.zs/new/VLN-CE/vlnce_baselines/common/recollection_dataset.py", line 49, in **init** self.initialize_sims() File "/home/zengshuang.zs/new/VLN-CE/vlnce_baselines/common/recollection_dataset.py", line 71, in initialize_sims observations = self.envs.reset() File "/home/zengshuang.zs/g3D-LF/habitat-lab/habitat/core/vector_env.py", line 384, in reset results.append(read_fn()) File "/home/zengshuang.zs/g3D-LF/habitat-lab/habitat/core/vector_env.py", line 97, in **call** res = self.read_fn() File "/home/zengshuang.zs/g3D-LF/habitat-lab/habitat/utils/pickle5_multiprocessing.py", line 68, in recv buf = self.recv_bytes() File "/home/zengshuang.zs/anaconda3/envs/vlnce/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes buf = self._recv_bytes(maxlength) File "/home/zengshuang.zs/anaconda3/envs/vlnce/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes buf = self._recv(4) File "/home/zengshuang.zs/anaconda3/envs/vlnce/lib/python3.6/multiprocessing/connection.py", line 383, in _recv raise EOFError EOFError Exception ignored in: <bound method VectorEnv.**del** of <habitat.core.vector_env.VectorEnv object at 0x7f62aae70518>> Traceback (most recent call last): File "/home/zengshuang.zs/g3D-LF/habitat-lab/habitat/core/vector_env.py", line 588, in **del** self.close() File "/home/zengshuang.zs/g3D-LF/habitat-lab/habitat/core/vector_env.py", line 456, in close read_fn() File "/home/zengshuang.zs/g3D-LF/habitat-lab/habitat/core/vector_env.py", line 97, in **call** res = self.read_fn() File "/home/zengshuang.zs/g3D-LF/habitat-lab/habitat/utils/pickle5_multiprocessing.py", line 68, in recv buf = self.recv_bytes() File "/home/zengshuang.zs/anaconda3/envs/vlnce/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes buf = self._recv_bytes(maxlength) File "/home/zengshuang.zs/anaconda3/envs/vlnce/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes buf = self._recv(4) File "/home/zengshuang.zs/anaconda3/envs/vlnce/lib/python3.6/multiprocessing/connection.py", line 383, in _recv raise EOFError EOFError:
